### ISSUE TITLE
HugeMCE fails to build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by mikkorantalainen** [hugemce/hugemce#7]
## 📝 Provide detailed reproduction steps (if any)

```shell_session
$ git clone https://github.com/hugemce/hugemce.git
$ cd hugemce
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tinymce-monorepo@undefined
npm ERR! Found: stylelint@13.13.1
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^13.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^14.0.0" from stylelint-order@5.0.0
npm ERR! node_modules/stylelint-order
npm ERR!   dev stylelint-order@"^5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/$USER/.npm/_logs/2024-09-04T07_48_43_244Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/$USER/.npm/_logs/2024-09-04T07_48_43_244Z-debug-0.log
```

### ✔️ Expected result

The `npm install` should have completed successfully without dependency failures. And I would expect `yarn build` then to complete the build successfully.

### ❌ Actual result

See the above shell session example. The default `package.json` contains conflicting version numbers for `stylelint` vs `stylelint-order`. It appears that `stylelint-order` version 5 is only supported with `stylelint` version 14 but the `package.json` requests for version 13 instead.

### ❓ Possible solution
Upgrade `stylelint` to version 14 and fix all the features that are no longer supported by `stylelint`.

Another option is to downgrade the `stylelint-order` requirement to version 4.

```diff
diff --git i/package.json w/package.json
index 448a1d43a2..8480c4a537 100644
--- i/package.json
+++ w/package.json
@@ -77,7 +77,7 @@
     "string-replace-loader": "^3.0.3",
     "stylelint": "^13.2.1",
     "stylelint-config-standard": "^20.0.0",
-    "stylelint-order": "^5.0.0",
+    "stylelint-order": "^4.0.0",
     "terser": "^5.17.4",
     "ts-loader": "^9.2.6",
     "tsconfig-paths-webpack-plugin": "^4.0.1",
```

This results in `npm install` completing succesfully (warns about 32 vulnerabilities in dependencies, though) but `yarn build` will then fail with following error

```shell_session
$ yarn build
yarn run v1.22.22
$ npm-run-all -p oxide-icons-ci oxide-ci -s tinymce-grunt
$ yarn -s --cwd modules/oxide ci
$ yarn -s --cwd modules/oxide-icons-default ci
[10:56:53] Using gulpfile ~/dev/hugemce/modules/oxide-icons-default/gulpfile.js
[10:56:53] Starting 'default'...
[10:56:53] Starting 'clean'...
[10:56:53] Finished 'clean' after 16 ms
[10:56:53] Starting 'icon-packager'...
[10:56:53] Using gulpfile ~/dev/hugemce/modules/oxide/gulpfile.js
[10:56:53] Starting 'build'...
[10:56:53] Starting 'clean'...
[10:56:53] Finished 'clean' after 29 ms
[10:56:53] Starting 'css'...
[10:56:53] Starting 'lint'...
[10:56:54] Finished 'icon-packager' after 574 ms
[10:56:54] Finished 'default' after 593 ms
[10:56:57] Finished 'lint' after 3.83 s
[10:56:57] Starting 'less'...
[10:56:58] Finished 'less' after 1.21 s
[10:56:58] Starting 'generateJs'...
[10:56:59] Finished 'generateJs' after 724 ms
[10:56:59] Starting 'minifyCss'...
[10:56:59] Finished 'minifyCss' after 300 ms
[10:56:59] Finished 'css' after 6.07 s
[10:56:59] Finished 'build' after 6.1 s
$ grunt --gruntfile modules/tinymce/Gruntfile.js
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "shell:prismjs" (shell) task

Running "shell:tsc" (shell) task
src/core/test/ts/browser/EditorTest.ts(404,28): error TS2339: Property 'type' does not exist on type 'never'.
Warning: Command failed: tsc -b
 Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "tinymce-grunt" exited with 6.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The error `error TS2339: Property 'type' does not exist on type 'never'.` seems to be about TypeScript compiler being unwilling to simply remove dead code during compilation. I don't know an easy way to solve this without modifying the code of the dependencies, which doesn't seem like a long term solution.

## 📃 Other details
- Browser: N/A
- OS: Ubuntu 22.04 LTS, 64 bit
- First affected version:
      $ git rev-parse HEAD
      02f35e9a88d0b5156d5680af9eb7dc6d1f8f9c3c
- Worked in version: unknown

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post instead of commenting "+1".

**Comment by carlosmintfan** [comment]
Don't use `npm install`, use `yarn` before running `yarn build`. See https://github.com/hugemce/hugemce/blob/e79c08b/CONTRIBUTING.md: This repo is built with Yarn workspaces and uses publish tooling support from Lerna. **NPM is not supported and attempts to use it will fail.**
`yarn build` will still make problems with the tests though, as I pasted in #1. I'll have to see how to resolve them – maybe it's because I deleted the lockfile. But why did yarn complain about it? Possibly because of integrity hashes?
Also, note that as I mentioned in https://github.com/hugemce/hugemce/commit/d4c8735436af7ce54a385f74f12a5569adfa20bf, you'll have to `yarn link` the packages. Yeah, it's hard: You'll have to run `yarn link` in every module and then `yarn link @hugemce/module-name` for every module – in every module (or just in the monorepo? But modules are dependent on others...) So you'd have to do some Bash-scripting.

**Comment by mikkorantalainen** [comment]
I tried to build with `yarn && yarn build` vs `npm install && yarn build` with my patches and the results seemed identical. The build was also equally slow and used barely 2 CPU cores.

**Comment by carlosmintfan** [comment]
Which dead code? The error in the tests ist just a stupidness of tsc, you think? So I may have to downgrade the version or so...

**Comment by mikkorantalainen** [comment]
When I compare the generated tinymce.js to the official 6.8.4 release, it seems that the file generated from HugeMCE includes lots of code that's included from `modules/katamari/src/main/ts/hugemce/katamari/api/Adt.ts` and its dependencies. None of that code is in the officially distributed TinyMCE files.

**Comment by carlosmintfan** [comment]
Hmm.
But how did you even get to build the package? Did you `yarn link` too?

**Comment by carlosmintfan** [comment]
If you revert the stylelint version change and the Grunt script change and only keep the ignore on the test - then use `yarn` instead of `npm install` - does everything work without errors?

**Comment by carlosmintfan** [comment]
> I don't know an easy way to solve this without modifying the code of the dependencies, which doesn't seem like a long term solution.

Of which dependencies? TinyMCE already patches dompurify...

**Comment by mikkorantalainen** [comment]
> Which dead code? The error in the tests is just a stupidness of tsc, you think? So I may have to downgrade the version or so...

I think `tsc` is simply too stupid. If you want, you can also copy the workaround the same file used above and do following:

```diff
diff --git i/modules/tinymce/src/core/test/ts/browser/EditorTest.ts w/modules/tinymce/src/core/test/ts/browser/EditorTest.ts
index 78fc1f0a2a..4db322d302 100644
--- i/modules/tinymce/src/core/test/ts/browser/EditorTest.ts
+++ w/modules/tinymce/src/core/test/ts/browser/EditorTest.ts
@@ -401,7 +401,7 @@ describe('browser.tinymce.core.EditorTest', () => {
     assert.isFalse(editor.isDirty(), 'setDirty/isDirty');
 
     editor.setDirty(true);
-    assert.equal(lastArgs?.type, 'dirty', 'setDirty/isDirty');
+    assert.equal((lastArgs as unknown as EditorEvent<{}>).type, 'dirty', 'setDirty/isDirty');
     assert.isTrue( editor.isDirty(), 'setDirty/isDirty');
 
     lastArgs = undefined;
```

That should be logically about the same thing, just with a lot more complex syntax to make `tsc` happy.

**Comment by mikkorantalainen** [comment]
When I do following:
```bash
git clone https://github.com/hugemce/hugemce.git
cd hugemce
yarn
yarn build
```
and run
```bash
diff -u <(curl --silent "https://cdn.jsdelivr.net/npm/tinymce@6.8.4/tinymce.js" | sed 's/[$].//g') <(cat js/tinymce/tinymce.js | sed 's/[$].//g') | grep -o '^[+-]' | sort | uniq -c
```

I get 

```text
  19749 +
   3385 -
```

That is, HugeMCE generated about 16K lines of extra code. A cursory peak to the differences suggests that most of the code is related to class `Adt`. I don't know what that's supposed to do but obviously it shouldn't be mandatory considering that the official TinyMCE distribution doesn't contain such code.

I'd expect some of the functions to be in different order relative to the official release (`tsc` doesn't support reproducible builds as far as I know) but the total amount of lines should be close.

**Comment by mikkorantalainen** [comment]
I agree that `packages.json` does work correctly as-is if you use `yarn` instead of `npm install` so I think that hack of my should be ignored.

**Comment by mikkorantalainen** [comment]
Maybe consider fast forwarding to https://github.com/mikkorantalainen/hugemce/tree/hugemce-fix-5 ?

(I prefer to never do GitHub pull requests because GitHub doesn't support true fast forward merges but if you prefer otherwise, I can do a pull request, too.)

With the above branch, there's no need to use `@ts-ignore` and you can successfully build the code with `yarn && yarn build` without running `yarn link` at all on Ubuntu 22.04 LTS.

Note that the NodeJS version officially supported on Ubuntu 22.04 LTS is too old to build this project so you have to install NodeJS from https://deb.nodesource.com/ – I installed NodeJS version v18.20.4 while testing this.

**Comment by carlosmintfan** [comment]
You can build without `yarn link`? Oh yeah, of course it should work cause it's a monorepo and all packages should be able to build together although they aren't published yet. But why did I have to? Probably I confused stuff and all errors were related to the packages not in the monorepo (where I had to revert the ephox -> hugemce replace).
So all these build errors were just the result of changing the stylelint version, right? I don't know why it works in `yarn` but is incompatible for `npm install` but as `yarn` is the suggested method, I'd just leave it as is.
And, yeah, I'm using nvm (node version manager) for having better Node.JS.
Then I think I can close this? I'll take your commit over; oh, how do you mean I should fast-forward it? The easiest would be that you do a PR and if you don't like merge commits, I merge it with the rebase option; but then your branch would be shown as "1 commit forward (or whatever it's called), 1 commit behind" HugeMCE main? Oh. As I'm not _that_ experienced with Git, maybe you could tell me how to fast-forward it.
And it would be great if you could share your opinion in #1 whether you think it's okay if migrating to HugeMCE requires global replacement of the `tinymce` object to `hugemce`, like `tinymce.init` to `hugemce.init`. I need your opinions to work correctly 😀

**Comment by carlosmintfan** [comment]
Wouldn’t you like to get an organization member, although not with main commit rights yet? You’re one of the most active people here and, after Rob Willie who contributed the Paste from Word plugin, actually made a small but very helpful code contribution. (Thank you very much!) So if you’d like to contribute further, I’ll be glad to show you off as an org member!

**Comment by mikkorantalainen** [comment]
> I don't know why it works in `yarn` but is incompatible for `npm install` but as `yarn` is the suggested method, I'd just leave it as is.

I think it's just caused by npm not being smart enough to figure out the dependencies. It seems that yarn is perfectly happy to use the version numbers defined in `package.json` but `npm install` thinks that there's some collision between the dependencies.

It appears that you can make npm accept the dependencies by installing those packages with different version numbers first and the upgrading or downgrading the packages until you get the same exact packages as defined in `package.json`. As such, that would be a bug in npm I'm not interested to figure out why it fails if yarn can do the same task without failing using the same input data.

The only problem I have with yarn is that it's not officially supported by NodeJS unlike npm which is included in the officially distributed NodeJS package.


> I'll take your commit over; oh, how do you mean I should fast-forward it? The easiest would be that you do a PR and if you don't like merge commits, I merge it with the rebase option; but then your branch would be shown as "1 commit forward (or whatever it's called), 1 commit behind" HugeMCE main? Oh. As I'm not _that_ experienced with Git, maybe you could tell me how to fast-forward it.

If you want to understand the lack of fast-forward in GitHub, see the discussion at https://github.com/orgs/community/discussions/4618

I've been using git with a software team over a decade and I'm nowadays thinking that one should target for linear history as much as possible. In pratice, this is easiest to achieve by having feature branches and rebasing those to current master/main branch and then simply "fast forward" the feature branch into master/main. However, you shouldn't make it a religion either way. Choose either rebase workflow or merge workflow depending on the situation. But I strongly think that rebase workflow (fast forward merge for you, rebase for the submitter) is the option you should choose nearly always if possible.

Fast forwarding means that when the new branch has the current master/main literally in the DAG, the feature branch can be incorporated into master/main simply by moving the master/main branch label to the feature branch. This results in zero new commits and doesn't change any SHA-1 in the history of either the master/main branch or the commits of feature branch.

However, as explained in the above discussion, GitHub doesn't support this at all. The only options that GitHub support are (1) true merge which results in extra commits at every time and (2) replaying the commits on top of the main/master branch. The (2) results in same count of commits but every commit is rewritten with new timestamps which changes every commit SHA-1 as a result.

As for how to do this in practice, you can simply do following on command line in your own working directory:

```bash
git fetch "https://github.com/mikkorantalainen/hugemce.git" hugemce-fix-5
git merge --ff-only FETCH_HEAD
```

And Git will the complain and do nothing if either step fails (e.g. the URL was incorrect or the merge cannot be completed as fast-forward but would create a true merge.

You can also fetch specific commit id with the same syntax. For example you could do
```bash
git fetch "https://github.com/mikkorantalainen/hugemce.git" bdf8d2e74112543a2f215b0f3b0c32b876c069c9
git merge --ff-only FETCH_HEAD
```
This style allows you to fetching some specific commit history even if the named branch had already been moved to somewhere else. The reference `FETCH_HEAD` is always updated to match the last successful fetch so you don't need to repeat the SHA-1 for the merge command – though if you want you can obviously write the SHA-1 instead of `FETCH_HEAD` here, too.

And if you don't blindly trust the given URL, it might be a good idea to check the fetched content before doing the fast-forward merge. I prefer to do `gitk HEAD FETCH_HEAD` but you can choose whatever method you want for reviewing the changes before accepting them.

> And it would be great if you could share your opinion in #1 whether you think it's okay if migrating to HugeMCE requires global replacement of the `tinymce` object to `hugemce`, like `tinymce.init` to `hugemce.init`. I need your opinions to work correctly 😀

I've been wondering the same thing but I don't have any strong opinion about that yet.

I would like to think that changing every name would be wasted effort and it would also make switching from TinyMCE to HugeMCE harder for the end users. On the other hand "TinyMCE" is a registered trademark of Tiny Technologies, Inc. so continuing it might end up being a trademark violation anyway so name change may be mandatory eventually.

That is, unless TinyMCE license change is reverted and in that case it would be better if this project hadn't swapped every string. If only my crystal ball would work...

**Comment by carlosmintfan** [comment]
@mikkorantalainen Thank you for your explanations. I'll fast-forward your branch then.
I'm now in favor of replacing all occurrences of TinyMCE. It may not be great for end users migrating, but actually they only need to do a bash command (I'll provide one), at clean working directory if possible, commit, and done. Other way, they'd have to change the package.json and the path to the file in node_modules but then they could still use the global window `tinymce` object although they'd have to change the path to the JS file? And should the file be named `tinymce.js` or `hugemce.js`? So I think I'll just do global replace.

**Comment by carlosmintfan** [comment]
The ADT is also in the official TinyMCE code:
![Screenshot demonstrating ADT in official TinyMCE code](https://github.com/user-attachments/assets/5b037e27-5209-405f-943b-626174eee149)

**Comment by carlosmintfan** [comment]
```
$ diff -u <(curl --silent "https://cdn.jsdelivr.net/npm/tinymce@6.8.4/tinymce.js" | sed 's/[$].//g') <(cat js/tinymce/tinymce.js | sed 's/[$].//g') | head -n 50
--- /dev/fd/63  2024-09-06 15:32:39.206815587 -0400
+++ /dev/fd/62  2024-09-06 15:32:39.206815587 -0400
@@ -21,6 +21,19 @@
       }
       return t;
     };
+    var isType = function (type) {
+      return function (value) {
+        return typeOf(value) === type;
+      };
+    };
+    var isString = isType('string');
+    var isObject = isType('object');
+    var isArray = isType('array');
+    var isNull = isType('null');
+    var isBoolean = isType('boolean');
+    var isUndefined = isType('undefined');
+    var isFunction = isType('function');
+    var isNumber = isType('number');
     var isEquatableType = function (x) {
       return [
         'undefined',
@@ -33,6 +46,18 @@
       ].indexOf(x) !== -1;
     };
 
+    var mapDelimit = function (xs, f, delimit) {
+      var len = xs.length;
+      var r = new Array(len);
+      for (var i = 0; i < len - 1; i++) {
+        var x = xs[i];
+        r[i] = delimit(f(x));
+      }
+      if (len > 0) {
+        r[len - 1] = f(xs[len - 1]);
+      }
+      return r;
+    };
     var sort = function (xs, compareFn) {
       var clone = Array.prototype.slice.call(xs);
       return clone.sort(compareFn);
@@ -50,6 +75,9 @@
       return x === y;
     });
     var eqString = tripleEq;
+    var eqNumber = tripleEq;
+    var eqUndefined = tripleEq;
+    var eqNull = tripleEq;
     var eqArray = function (eqa) {
       return eq(function (x, y) {
```
This looks like...more boilerplate? Maybe I'll have to downgrade somethink like webpack.

**Comment by carlosmintfan** [comment]
We need to bump some deps also; I'm trying to build not with the webpack version without carrot `^` and I also removed the carrot from typescript and got
```
Running "shell:tsc" (shell) task
src/core/main/ts/delete/DetailsDelete.ts(232,16): error TS2339: Property 'modify' does not exist on type 'Selection'.
```

**Comment by carlosmintfan** [comment]
Hmm, removing the carrot doesn't help...

**Comment by carlosmintfan** [comment]
This'll be a now issue.

**Comment by carlosmintfan** [comment]
#8
